In [3]:
import pandas as pd

In [4]:
data={
    "name":["arun","bala","dinesh","francis"],
    "age":[26,23,21,18],
    "location":["cbe","che","madurai","tn"],
    "id":["aa101","aa102","aa103","aa104"],
    "bloodgroup":["A1+","A+","B-","AB-"],
    "Roles":["Sales","HR","Clerk","Developer"],
    "Contact":[98663,76438,17373,95383],
    "Salary":[30000,80000,20000,50000]
}
df=pd.DataFrame(data)
print(df)

      name  age location     id bloodgroup      Roles  Contact  Salary
0     arun   26      cbe  aa101        A1+      Sales    98663   30000
1     bala   23      che  aa102         A+         HR    76438   80000
2   dinesh   21  madurai  aa103         B-      Clerk    17373   20000
3  francis   18       tn  aa104        AB-  Developer    95383   50000

In [5]:
data=pd.read_csv("patients.csv")
df=pd.DataFrame(data)
df.head()

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,phone,email,address,city,state,emergency_contact,registration_date
0,1,Patient1,Kumar,Male,1995-01-01,31,A+,9876510001,patient1@example.com,1 Main Road,Coimbatore,Tamil Nadu,9123410001,2026-01-01
1,2,Patient2,Kumar,Female,1995-01-01,32,B+,9876510002,patient2@example.com,2 Main Road,Madurai,Tamil Nadu,9123410002,2026-01-01
2,3,Patient3,Kumar,Male,1995-01-01,33,AB+,9876510003,patient3@example.com,3 Main Road,Salem,Tamil Nadu,9123410003,2026-01-01
3,4,Patient4,Kumar,Female,1995-01-01,34,O-,9876510004,patient4@example.com,4 Main Road,Erode,Tamil Nadu,9123410004,2026-01-01
4,5,Patient5,Kumar,Male,1995-01-01,35,O+,9876510005,patient5@example.com,5 Main Road,Chennai,Tamil Nadu,9123410005,2026-01-01

In [6]:
data=pd.read_csv("patients.csv")
df=pd.DataFrame(data)
df.tail()

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,phone,email,address,city,state,emergency_contact,registration_date
95,96,Patient96,Kumar,Female,1995-01-01,36,A+,9876510096,patient96@example.com,96 Main Road,Coimbatore,Tamil Nadu,9123410096,2026-01-01
96,97,Patient97,Kumar,Male,1995-01-01,37,B+,9876510097,patient97@example.com,97 Main Road,Madurai,Tamil Nadu,9123410097,2026-01-01
97,98,Patient98,Kumar,Female,1995-01-01,38,AB+,9876510098,patient98@example.com,98 Main Road,Salem,Tamil Nadu,9123410098,2026-01-01
98,99,Patient99,Kumar,Male,1995-01-01,39,O-,9876510099,patient99@example.com,99 Main Road,Erode,Tamil Nadu,9123410099,2026-01-01
99,100,Patient100,Kumar,Female,1995-01-01,30,O+,9876510100,patient100@example.com,100 Main Road,Chennai,Tamil Nadu,9123410100,2026-01-01

In [ ]:
df.isnull().sum()

patient_id           0
first_name           0
last_name            0
gender               0
date_of_birth        0
age                  0
blood_group          0
phone                0
email                0
address              0
city                 0
state                0
emergency_contact    0
registration_date    0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [1]:
# ensure the dataframe is loaded first
data = pd.read_csv("patients.csv")
df = pd.DataFrame(data)

df.drop("patient_id", axis=1)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
file_path = "patients.csv"
df = pd.read_csv(file_path)
df

,patient_id,first_name,last_name,gender,date_of_birth,age,blood_group,phone,email,address,city,state,emergency_contact,registration_date
0,1,Patient1,Kumar,Male,1995-01-01,31,A+,9876510001,patient1@example.com,1 Main Road,Coimbatore,Tamil Nadu,9123410001,2026-01-01
1,2,Patient2,Kumar,Female,1995-01-01,32,B+,9876510002,patient2@example.com,2 Main Road,Madurai,Tamil Nadu,9123410002,2026-01-01
2,3,Patient3,Kumar,Male,1995-01-01,33,AB+,9876510003,patient3@example.com,3 Main Road,Salem,Tamil Nadu,9123410003,2026-01-01
3,4,Patient4,Kumar,Female,1995-01-01,34,O-,9876510004,patient4@example.com,4 Main Road,Erode,Tamil Nadu,9123410004,2026-01-01
4,5,Patient5,Kumar,Male,1995-01-01,35,O+,9876510005,patient5@example.com,5 Main Road,Chennai,Tamil Nadu,9123410005,2026-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Patient96,Kumar,Female,1995-01-01,36,A+,9876510096,patient96@example.com,96 Main Road,Coimbatore,Tamil Nadu,9123410096,2026-01-01
96,97,Patient97,Kumar,Male,1995-01-01,37,B+,9876510097,patient97@example.com,97 Main Road,Madurai,Tamil Nadu,9123410097,2026-01-01
97,98,Patient98,Kumar,Female,1995-01-01,38,AB+,9876510098,patient98@example.com,98 Main Road,Salem,Tamil Nadu,9123410098,2026-01-01
98,99,Patient99,Kumar,Male,1995-01-01,39,O-,9876510099,patient99@example.com,99 Main Road,Erode,Tamil Nadu,9123410099,2026-01-01
99,100,Patient100,Kumar,Female,1995-01-01,30,O+,9876510100,patient100@example.com,100 Main Road,Chennai,Tamil Nadu,9123410100,2026-01-01